version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3005:3005
networks:
  # 如果没有其他服务共享网络，可以完全移除networks部分
  # 保留此部分是因为可能存在未展示的服务或未来扩展需要
  common-network:
    driver: bridge
